name: Crowdin Branch Clean-Up

on:
  pull_request:
    types: [synchronize, closed]
    branches:
        - 'master*'

jobs:
  delete_translation_branch:
    runs-on: ubuntu-latest
    if:  startsWith(github.head_ref, 'translation-') && startsWith(github.head_ref, 'stp-')
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "14.x"
      - run: npm i -g @crowdin/cli
      - run: npm ci
      - name: Delete Crowdin Branch ğŸ—‘ï¸
        run: crowdin branch delete ${{ github.head_ref }} -T ${{ secrets.CROWDIN_API_KEY }}
