name: Crowdin Branch Clean-Up

on:
  pull_request:
    types: [closed]
    branches:
        - 'master*'

jobs:
  delete_translation_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - name: Checking branch name (âŒ Auto stop on non-translation branches)
        run: exit 1
        if:  "!startsWith(steps.branch-name.outputs.head_ref_branch, 'translation-') && !startsWith(steps.branch-name.outputs.head_ref_branch, 'stp-')"
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "14.x"
      - run: npm i -g @crowdin/cli
      - run: npm ci
      - name: Git Setup
        run: echo "Setting up Git identity"
          git config --global user.name "DerivFE"
          git config --global user.email "80095553+DerivFE@users.noreply.github.com"
      - name: Delete Crowdin Branch ğŸ—‘ï¸
        run: crowdin branch delete ${{ steps.branch-name.outputs.head_ref_branch }} -T ${{ secrets.CROWDIN_API_KEY }}
