name: Generate preview link

permissions:
    actions: write
    checks: write
    contents: write
    deployments: write
    pull-requests: write
    statuses: write

on:
    workflow_run:
        workflows: ['Pre-generate preview link']
        types:
            - completed

env:
    NODE_OPTIONS: '--max-old-space-size=8192'

concurrency:
    group: cloudflare-pages-build-${{ github.event.workflow_run.head_branch }}
    cancel-in-progress: true

jobs:
    build_to_cloudflare_pages:
        runs-on: Ubuntu-latest
        if: >
            github.event.workflow_run.event == 'pull_request' &&
            github.event.workflow_run.conclusion == 'success'
        steps:
            - name: Download artifact
              id: download-artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow_conclusion: success
                  run_id: ${{ github.event.workflow_run.id }}
                  name: 'pr-${{ github.event.workflow_run.id }}'

            - name: Retrieve pull request
              id: pr_information
              run: |
                  echo "issue_number=$(cat ./NR)" > $GITHUB_OUTPUT

            - name: 'Generate action link comment'
              id: generate_action_url
              uses: actions/github-script@v3
              with:
                  github-token: ${{ github.token }}
                  script: |
                      const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
                      const comment = [
                          '| Name | Result |',
                          '| :--- | :------ |',
                          `| **Build status**  | Building üî® |`,
                          `| **Action URL**  | [Visit Action](${action_url}) |`,
                          ''
                        ].join('\n')
                      core.setOutput("comment", comment);
            - name: Post Cloudflare Pages Preview comment
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: Cloudflare Pages Preview Comment
                  number: ${{steps.pr_information.outputs.issue_number}}
                  message: ${{steps.generate_action_url.outputs.comment}}
                  recreate: true

            - name: Verify user organization
              id: verify_user_organization
              run: |
                  echo "Verifying user's organization..."
                  user=$(cat ./USERNAME)
                  response=$(curl -s -L \
                      -w "%{http_code}" \
                     -o /dev/null -H "Accept: application/vnd.github+json" \
                     -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
                     -H "X-GitHub-Api-Version: 2022-11-28" \
                     "https://api.github.com/orgs/binary-com/memberships/$user")
                     
                  if [ $response != "200" ]; then
                      echo "User is not a member of binary-com organization."
                      exit 1
                  else
                      echo "User is a member of binary-com organization."
                      echo "Proceeding to build and deploy for the pull request: https://github.com/binary-com/deriv-com/pull/$(cat ./NR)"
                  fi
            - name: Checkout to repo
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.workflow_run.head_sha }}

            - name: Setup node
              uses: actions/setup-node@v2

            - name: Get build output from master cache
              uses: actions/cache/restore@v3
              with:
                  key: master-cache-public
                  restore-keys: |
                      master-cache-public-replica
                  path: |
                      .cache
                      public
            - name: Get cached dependencies
              id: cache-npm
              uses: actions/cache/restore@v3
              with:
                  path: node_modules
                  key: npm-${{ hashFiles('**/package-lock.json') }}

            - name: Install dependencies
              if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              run: npm ci

            - name: Build project
              id: build-project
              run: npm run build

            - name: Publish to Cloudflare Pages
              id: publish-to-pages
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TEST_LINKS_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_TEST_LINKS_ACCOUNT_ID }}
              run: |
                  echo "Installing Wrangler CLI"
                  npm i -g wrangler
                  echo "Deploying build to Cloudflare Pages"
                  directory='public'
                  projectName='deriv-com-preview-links'
                  head_branch=${{github.event.workflow_run.head_branch}}
                  branch=$(echo $head_branch | head -c 20)
                  preview_url=$(wrangler pages deploy $directory --project-name=$projectName --branch=$branch > log.txt 2>&1; echo $?)
                  echo "------"
                  cat log.txt
                  branchName=$(echo $branch | sed 's/[\/_\.]/-/g')
                  if grep -q "Deployment complete" log.txt; then
                    echo "preview_url=https://$branchName.deriv-com-preview-links.pages.dev" > "$GITHUB_OUTPUT"
                  else
                    echo "Deployment to Cloudflare Pages failed."
                    exit 1
                  fi
            - name: 'Generate preview link comment'
              if: success()
              id: generate_preview_url
              uses: actions/github-script@v3
              with:
                  github-token: ${{ github.token }}
                  script: |
                      const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
                      const preview_url = "${{steps.publish-to-pages.outputs.preview_url}}"
                      const comment = [
                          `**Preview Link**: ${preview_url}`,
                          '| Name | Result |',
                          '| :--- | :------ |',
                          `| **Build status**  | Completed ‚úÖ |`,
                          `| **Preview URL**  | [Visit Preview](${preview_url}) |`,
                          `| **Action URL**  | [Visit Action](${action_url}) |`,
                          ''
                        ].join('\n')
                      core.setOutput("comment", comment);
            - name: 'Generate failure comment'
              if: failure()
              id: generate_failure_comment
              uses: actions/github-script@v3
              with:
                  github-token: ${{ github.token }}
                  script: |
                      const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
                      const comment = [
                        '| Name | Result |',
                        '| :--- | :------ |',
                        `| **Build status**  | Failed ‚ùå |`,
                        `| **Action URL**  | [Visit Action](${action_url}) |`,
                        ''
                      ].join('\n')
                      core.setOutput("comment", comment);
            - name: Post Cloudflare Pages Preview comment
              if: always()
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: Cloudflare Pages Preview Comment
                  number: ${{steps.pr_information.outputs.issue_number}}
                  message: ${{steps.generate_preview_url.outputs.comment}}
                  recreate: true
