name: Translation Push

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
        - 'master*'
        
jobs:
    push-translation:
        runs-on: ubuntu-latest
        steps:
            - name: Get branch name
              id: branch-name
              uses: tj-actions/branch-names@v5.2
            - name: Checking branch name (‚ùå Auto stop on non-translation branches)
              run: exit 1
              if:  "!startsWith(steps.branch-name.outputs.head_ref_branch, 'translation-') && !startsWith(steps.branch-name.outputs.head_ref_branch, 'stp-')"
            - name: Checkout üõéÔ∏è
              uses: actions/checkout@v2.3.1
            - name: Setup Node
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: '14.x'
            - run: npm i -g @crowdin/cli
            - run: npm ci
            - name: Git Setup
              run: 
                  echo "Setting up Git identity"
                  git config --global user.name "DerivFE"
                  git config --global user.email "80095553+DerivFE@users.noreply.github.com"
            - name: Push New Strings & Translations ‚¨ÜÔ∏è
              run:  
                  crowdin upload sources -b ${{ steps.branch-name.outputs.head_ref_branch }} -T ${{ secrets.CROWDIN_API_KEY }}; crowdin upload translations -b ${{ steps.branch-name.outputs.head_ref_branch }} -T ${{ secrets.CROWDIN_API_KEY }}
                

