name: Delete Translation

on:
  workflow_run:
    workflows: ["Pre-delete Translation"]
    types:
      - completed
      
jobs:
    delete-translation:
        if: startsWith(github.event.workflow_run.head_branch, 'translation') || startsWith(github.event.workflow_run.head_branch, 'stp')
        runs-on: ubuntu-latest
        steps:
            - name: 'Branch [${{ github.event.workflow_run.head_branch }}]'
              run: echo 'Deleting Translation Branch ${{ github.event.workflow_run.head_branch }}'
            - name: Checkout üõéÔ∏è
              uses: actions/checkout@v2.3.1
              with:
                fetch-depth: 0
                ref: ${{ github.event.workflow_run.head_branch }}
                repository: ${{github.event.workflow_run.head_repository.full_name}}
            - name: Setup Node
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: '18.x'
            - name: Installing Crowdin     
              run: npm i -g @crowdin/cli
            - name: Delete Branch [${{ github.event.workflow_run.head_branch }}] üóëÔ∏è
              run: crowdin branch delete ${{ github.event.workflow_run.head_branch }} -T ${{ secrets.CROWDIN_API_KEY }}
                

